"""Add fields in the table 'defect': safety, load, exploitation, localized

Revision ID: 73dbb2852f71
Revises: 
Create Date: 2024-02-08 09:30:17.790971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73dbb2852f71'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defect', sa.Column('defect_safety', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('defect', sa.Column('defect_load', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('defect', sa.Column('defect_exploitation', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('defect', sa.Column('defect_localized', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defect', 'defect_localized')
    op.drop_column('defect', 'defect_exploitation')
    op.drop_column('defect', 'defect_load')
    op.drop_column('defect', 'defect_safety')
    # ### end Alembic commands ###
