"""add table division_ad

Revision ID: d36f5acf65fe
Revises: fc36ca9e16fb
Create Date: 2024-03-13 16:06:25.379223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from db.create_db import DIVISIONS
from db.division import Division
from db.division_ad import DivisionAD


# revision identifiers, used by Alembic.
revision: str = 'd36f5acf65fe'
down_revision: Union[str, None] = 'fc36ca9e16fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('division_ad',
    sa.Column('divisionAD_id', sa.Integer(), nullable=False),
    sa.Column('divisionAD_name', sa.String(length=200), nullable=False),
    sa.Column('divisionAD_division_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['divisionAD_division_id'], ['division.division_id'], ),
    sa.PrimaryKeyConstraint('divisionAD_id'),
    sa.UniqueConstraint('divisionAD_name')
    )

    # ### end Alembic commands ###
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    for division in DIVISIONS:
        division_name = division[0]
        divisions_AD = division[1]

        query = sa.select(Division).where(Division.division_name == division_name)
        result = session.scalars(query)
        division = result.one()
        for division_AD in divisions_AD:
                divisionAD =  DivisionAD(divisionAD_name=division_AD, divisionAD_division_id=division.division_id)
                session.add(divisionAD)        
    session.commit()

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('division_ad')
    # ### end Alembic commands ###
