"""add teble category_reason

Revision ID: f9bace459074
Revises: 8681260d905c
Create Date: 2024-02-14 16:03:15.995993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm

from db.create_db import CATEGORIES_REASON
from db.category_reason import CategoryReason

# revision identifiers, used by Alembic.
revision: str = 'f9bace459074'
down_revision: Union[str, None] = '8681260d905c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_reason',
    sa.Column('category_reason_code', sa.String(length=3), nullable=False),
    sa.Column('category_reason_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('category_reason_code'),
    sa.UniqueConstraint('category_reason_name')
    )
    # ### end Alembic commands ###
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    for category_reason in CATEGORIES_REASON:
            categoryreason = CategoryReason(category_reason_code=category_reason[0], category_reason_name=category_reason[1])
            session.add(categoryreason)
    session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_reason')
    # ### end Alembic commands ###
