"""fix bugs

Revision ID: fc36ca9e16fb
Revises: 668c0a5a7fc1
Create Date: 2024-02-16 15:42:09.171662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc36ca9e16fb'
down_revision: Union[str, None] = '668c0a5a7fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category_direct_reason', 'category_reason_code',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('defect', 'defect_direct_category_reason_code',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('defect', 'defect_direct_category_reason_code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=3),
               existing_nullable=True)
    op.alter_column('category_direct_reason', 'category_reason_code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    # ### end Alembic commands ###
